(map load '("strings.arc"
            "pprint.arc"
            "lib/extend.arc"
            "lib/scheme.arc"
;            "code.arc"
;            "html.arc"
;            "srv.arc"
;            "app.arc"
;            "prompt.arc"
            ))
